routes/web.php
<?php

use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::post('/create/user', 'UserController@create')->name('users.create');
// Route::post('/users', 'UserController@store')->name('users.store');
// Route::post('/login', 'UserController@login');
// Route::get('/', 'TransactionController@index');
// Route::get('/deposit', 'TransactionController@deposit');
// Route::post('/deposit', 'TransactionController@storeDeposit');
// Route::get('/withdrawal', 'TransactionController@withdrawal');
// Route::post('/withdrawal', 'TransactionController@storeWithdrawal');

Route::controller(UserController::class)
    ->prefix('users')
    ->as('users.')
    ->group(function () {
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
    });

Route::controller(TransactionController::class)
    ->prefix('transactions')
    ->as('transactions.')
    ->group(function () {
        Route::post('/store', 'store')->name('store');
        // Route::get('/create', 'create')->name('create');
        // Route::post('/store', 'store')->name('store');
        // Route::get('/show/{transaction}', 'show')->name('show');
        // Route::get('/edit/{transaction}', 'edit')->name('edit');
        // Route::post('/update/{transaction}', 'update')->name('update');
        // Route::get('/destroy/{transaction}', 'destroy')->name('destroy');
        // Route::get('/status/{transaction}', 'status')->name('status');
    });

Route::get('login', [UserController::class, 'loginForm'])->name('login')->middleware('guest');
Route::post('login', [UserController::class, 'login'])->name('login')->middleware('guest');
Route::get('dashboard', [UserController::class, 'dashboard'])->name('dashboard')->middleware('auth');
Route::get('signout', [UserController::class, 'signOut'])->name('signout');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name', 'account_type', 'balance', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
        'account_type' => 'string',
    ];

    public function withdrawals(): HasMany
    {
        return $this->hasMany(Transaction::class)->where('transaction_type', 'Withdrawal');
    }

    public function deposits(): HasMany
    {
        return $this->hasMany(Transaction::class)->where('transaction_type', 'Deposit');
    }

    public function withdrawalsThisMonth()
    {
        $currentMonth = Carbon::now()->format('Y-m');

        return $this->transactions()
            ->where('transaction_type', 'Withdrawal')
            ->whereYear('date', Carbon::now()->year)
            ->whereMonth('date', Carbon::now()->month)
            ->count();
    }
    
    public function totalWithdrawals()
    {
        return $this->transactions()
            ->where('transaction_type', 'Withdrawal')
            ->sum('amount');
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    public function create()
    {
        return view('user.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
            'account_type' => 'required|in:individual,business',
            'balance' => 'nullable|numeric',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6',
        ]);

        if ($validator->fails()) {
            return redirect()
                ->back()
                ->withErrors($validator)
                ->withInput();
        }

        $validated = $validator->validated();

        $validated['password'] = Hash::make($validated['password']);

        User::create($validated);
        return redirect()->route('login');
    }

    public function loginForm()
    {
        return view('auth.login');
    }

    public function login(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required',
            'password' => 'required',
        ]);

        $credentials = $request->only('email', 'password');
        if (Auth::attempt($credentials)) {
            return redirect()->intended('dashboard')
                        ->withSuccess('Signed in');
        }

        return redirect("login")->withErrors('Login details are not valid');
    }

    public function dashboard()
    {
        if(Auth::check()){
            $user = Auth::user();
            $data = [
                'balance' => $user->balance,
                'withdrawals' => $user->withdrawals,
                'deposits' => $user->deposits
            ];

            return view('user.dashboard', compact('data'));
        }


        return redirect("login")->withErrors('You are not allowed to access');
    }

    public function signOut() {
        Session::flush();
        Auth::logout();

        return Redirect('login');
    }
}

resources/views/user/create.blade.php
@extends('app')
@section('contant')
    <div class="alert alert-success mt-5" role="alert">
        <h3>Create User</h3>
    </div>
    <form method="POST" action="{{ route('users.store') }}">
        @csrf

        @include('inc.message')

        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" required>
        </div>

        <div class="mb-3">
            <label for="account_type" class="form-label">Account Type</label>
            <select class="form-select" id="account_type" name="account_type" required>
                @foreach(\App\Enums\TransactionType::toSelectArray() as $value => $label)
                    <option value="{{ $value }}">{{ $label }}</option>
                @endforeach
            </select>
        </div>

        <div class="mb-3">
            <label for="balance" class="form-label">Balance</label>
            <input type="number" class="form-control" id="balance" name="balance" placeholder="Enter balance" required>
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" required>
        </div>

        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" required>
        </div>

        <button type="submit" class="btn btn-primary mb-5">Create</button>
    </form>
@endsection

resources/views/user/dashboard.blade.php
@extends('app')
@section('contant')
    <div class="alert alert-success mt-5" role="alert">
        <h3>Dashboard</h3>
        <h6>
            Name: {{ Auth::user()->name }}
        </h6>
        Balance: {{ $data['balance'] }}
    </div>
    @include('inc.message')

    <div class="row">
        <h4 class="text-center text-bg-secondary p-3">Banking Transaction Form</h4>
        <form method="POST" action="{{ route('transactions.store') }}">
            @csrf
            <div class="mb-3">
                <label for="amount" class="form-label">Amount</label>
                <input type="number" class="form-control" id="amount" name="amount" placeholder="Enter amount" required>
            </div>

            <div class="mb-3">
                <label for="transaction_type" class="form-label">Transaction Type</label>
                <select class="form-select" id="transaction_type" name="transaction_type" required>
                    @foreach (\App\Enums\TransactionType::toSelectArray() as $value => $label)
                        <option value="{{ $value }}">{{ $label }}</option>
                    @endforeach
                </select>
            </div>

            <button type="submit" class="btn btn-success mb-5">Transaction</button>
        </form>
    </div>

    <div class="row">
        <h4 class="text-center text-bg-secondary p-3">Withdrawals</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Fee</th>
                    <th scope="col">Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data['withdrawals'] as $key => $item)
                    <tr>
                        <th scope="row">{{ ++$key }}</th>
                        <td>{{ $item->amount }}</td>
                        <td>{{ $item->fee }}</td>
                        <td>{{ $item->date }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="row">
        <h4 class="text-center text-bg-secondary p-3">Deposits</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Fee</th>
                    <th scope="col">Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data['withdrawals'] as $key => $item)
                    <tr>
                        <th scope="row">{{ ++$key }}</th>
                        <td>{{ $item->amount }}</td>
                        <td>{{ $item->fee }}</td>
                        <td>{{ $item->date }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection